apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gok8s-teste
  labels: 
    app: gok8s-teste
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gok8s-teste
  template:
    metadata:
      labels:
        app: gok8s-teste
    spec: 
      containers:
        - name: gok8s-teste
          image: chmenegatti/gok8s
          ports:
            - containerPort: 3001
          env: 
          - name: DB_USER
            value: postgres
          - name: DB_PASS
            value: password
          - name: DB_NAME
            value: cadastro
          - name: DB_URL
            value: postgres-svc
          - name: DB_PORT
            value: '5432'
          - name: PORT
            value: '3001'


